=== smart-data-models/drafted_models/ConsumptionBehaviour_2023_06_26_14_33/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$schemaVersion": "0.0.1",
  "$id": "https://smart-data-models.github.io/dataModel.TourismDestinations/ConsumptionBehaviour/schema.json,",
  "title": "Consumption Behaviour",
  "description": "This model is designed to record and track the consumption of various resources such as electricity, diesel, and water over a specified period.",
  "modelTags": "",
  "derivedFrom": "",
  "required": [
    "id",
    "type"
  ],
  "license": "https://smart-data-models.github.io/dataModel.TourismDestinations/ConsumptionBehaviour/LICENSE.md",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uri"
    },
    "type": {
      "type": "string",
      "enum": [
        "ConsumptionBehaviour"
        ],
        "description": "Property. Entity type ConsumptionBehaviour."
    },
    "sourceOfConsumption": {
      "$ref": "https://smart-data-models.github.io/data-models/common-schema.json#/definitions/EntityIdentifierType",
      "description": "Relationship. The object that is generating the consumption."
    },
    "startDate": {
      "type": "string",
      "format": "date-time",
      "description": "Property. Start date of the consumption."
    },
    "endDate": {
      "type": "string",
      "format": "date-time",
      "description": "Property. End date of the consumption."
    },
    "resourceType": {
      "type": "string",
      "enum": ["Diesel","Petrol","Electricity","Gas","Water"],
      "description": "Property. Type of resource consumed."
    },
    "initialMeasurement": {
      "type": "number",
      "description": "Property. Initial measurement of the resource."
    },
    "finalMeasurement": {
      "type": "number",
      "description": "Property. Final measurement of the resource."
    },
    "usersInvolved": {
      "type": "number",
      "description": "Property. Number of persons/users involved in the consumption."
    }
  }
}

=== smart-data-models/drafted_models/ConsumptionBehaviour_2023_06_26_14_33/examples/example.json
{
    "id": "urn:ngsi-ld:ConsumptionBehaviour:VC17",
    "type": "ConsumptionBehaviour",
    "resourceType": "Diesel",
    "sourceOfConsumption": "urn:ngsi-ld:Vehicle:VC0001",
    "startDate": "2018-09-21T12:00:00Z",
    "endDate": "2018-09-21T12:00:00Z",
    "initialMeasurement": 455555,
    "finalMeasurement": 456123,
    "usersInvolved": 2
}
