=== smart-data-models/drafted_models/FuelCell_2025_04_22_12_08/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$schemaVersion": "0.0.1",
  "$id": "https://smart-data-models.github.io/dataModel.EnergyStorage/FuelCell/schema.json,",
  "title": "Fuel cell data model",
  "description": "A generic fuel cell which can generate energy from hydrogen",
  "modelTags": "",
  "derivedFrom": "",
  "required": [
    "id",
    "type"
  ],
  "license": "https://smart-data-models.github.io/dataModel.EnergyStorage/FuelCell/LICENSE.md",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uri",
      "description": "Property. Unique ID of the object"
    },
    "type": {
      "type": "string",
      "description": "Property. Title of the form element"
    },
    "description": {
      "type": "string",
      "description": "Property. Description of the element"
    },
    "location": {
      "type": "object",
      "description": "GeoProperty. Location",
      "properties": {}
    },
    "status": {
      "type": "string",
      "description": "Property. Status: ON/OFF"
    },
    "name": {
      "type": "string",
      "description": "Property. Name of the object"
    },
    "maxHydrogenFlowConsumed": {
      "type": "number",
      "description": "Property. Maximum hydrogen flow consumed (Nl/h)"
    },
    "maxPowerGenerated": {
      "type": "number",
      "description": "Property. Maximum power produced (W)"
    }
  }
}

=== smart-data-models/drafted_models/FuelCell_2025_04_22_12_08/examples/example.json
{
    "id": "urn:ngsi-ld:FuelCell:santander:EnergyStorage:fuelCell:0001",
    "type": "FuelCell",
    "description": "mixed generator model ~004 with maximum power 22w",
    "location": {
        "type": "Point",
        "coordinates": [
            -4.184943709787973,
            43.379971307869766
        ]
    },
    "status": "ON",
    "name": "FuelCell #0001",
    "maxHydrogenFlowConsumed": 3000,
    "maxPowerGenerated": 600
}
