=== smart-data-models/drafted_models/DataModelVersion_2023_09_07_15_00/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$schemaVersion": "0.0.1",
  "$id": "https://smart-data-models.github.io/dataModel.SDM/DataModelVersion/schema.json,",
  "title": "Descriptors of a version of a data model curated at the Smart Data Models initiative",
  "description": "it stores the main data about a specific version of a data model curate at the smart datamodels initiative",
  "modelTags": "",
  "derivedFrom": "",
  "required": [
    "id",
    "type"
  ],
  "license": "https://smart-data-models.github.io/dataModel.SDM/DataModelVersion/LICENSE.md",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uri",
      "description": "Property. Unique Id of the entity"
    },
    "type": {
      "type": "string",
      "enum": [
        "DataModelVersion"
      ],
      "description": "Property. It has to be DataModelVersion"
    },
    "subject": {
      "type": "string",
      "description": "Property. Subject of the data model"
    },
    "dataModel": {
      "type": "string",
      "description": "Property. Data model name"
    },
    "version": {
      "type": "string",
      "description": "Property. Version of the data model"
    },
    "date": {
      "type": "string",
      "format": "date-time",
      "description": "Property. Date of the commit of the current data model"
    },
    "url": {
      "type": "string",
      "format": "uri",
      "description": "Property. URL to the github repository where the data model version is published"
    },
    "commit": {
      "type": "string",
      "description": "Property. Hash of the commit of the data model version"
    }
  }
}

=== smart-data-models/drafted_models/DataModelVersion_2023_09_07_15_00/examples/example.json
{
    "id": "urn:ngsi-ld:0001",
    "type": "DataModelVersion",
    "subject": "dataModel.TourismDestinations",
    "dataModel": "Event",
    "version": "0.0.1",
    "date": "10/05/2021 05:04 PM",
    "url": "https://raw.githubusercontent.com/smart-data-models/dataModel.TourismDestinations/9a98d426f9de88de3c28a5b88a95485fae333d17/Event/schema.json"
}
